### ISSUE TITLE
White listed folder?

### ISSUE THREAD

**Issue by jan-vince** [magenizr/October_Envbar#1]
After install I get 404 for file `/storage/temp/magenizr.envbar.style.css?1.0.1`.

When I put `/storage/temp` folder in .htaccess, it works:

`RewriteCond %{REQUEST_FILENAME} !/storage/temp/.*`

Maybe move the file to `/storage/temp/public` folder which is allowed by default in OctoberCMS .htaccess file?

Or maybe I am missing something?

**Comment by magenizr** [comment]
Hey Jan,

Good catch, thank you for that. We will provide a new release later this afternoon.

Cheers

**Comment by jan-vince** [comment]
Cool :)

**Comment by magenizr** [comment]
The new release is available.

```
php artisan plugin:install Magenizr.Envbar
Downloading plugin: Magenizr.Envbar
Unpacking plugin: Magenizr.Envbar
Migrating plugin...
Magenizr.Envbar
- v1.0.2:  Change path for compiled CSS file from ./storage/temp to ./storage/temp/public.
```
