### ISSUE TITLE
Check env on every pageload.

### ISSUE THREAD

**Issue by kavishdahekar** [magenizr/October_Envbar#3]
If I temporarily change env on my local system just to check if the colors change, they don't.
I have to disable and enable to see the color change everytime I change the environment.

Maybe the plugin checks the env only on certain events instead of on every page load.

**Comment by magenizr** [comment]
Hi @kavishdahekar 

Thank you for playing around with the .env file and logging the issue. Correct, the plugin doesn't read the .env file on every page load, mainly because the .env file doesn't change very often.

However, we have an idea of how this can be improved and provide an update asap.

Thanks,
Tobias

**Comment by magenizr** [comment]
Hi @kavishdahekar 

Actually, the following method in `./plugins/magenizr/envbar/models/Settings.php` will clear the cache once you save the settings again.

```
/**
 * Clear cache after saving settings.
 */
public function afterSave()
{
    Cache::forget(self::instance()->cacheKey);
}
```

However, we will have a look if this can be done automatically.

**Comment by kavishdahekar** [comment]
Hey @magenizr , thanks for taking a look at this.
Will keep an eye out for whenever you push a fix.

**Comment by magenizr** [comment]
Hi @kavishdahekar 

A new version has been published. Use artisan to install the latest version or just pull from Github.

```
bash-4.4# php artisan plugin:install Magenizr.Envbar
Downloading plugin: Magenizr.Envbar
Unpacking plugin: Magenizr.Envbar
Migrating plugin...
Magenizr.Envbar
- v1.0.3:  Automatically clear cached styles ( colors ) if `.env` file has been updated.
```

Thanks,
Tobias
